title = "Neo"
base_url = "https://nikoook.github.io/niko-zola-blog"

theme = "terminimal"
compile_sass = true

taxonomies = [
    {name = "tags"},
]

[markdown]
highlight_code = true

[extra]
accent_color = "blue"
background_color = "dark"
author = "Neo"

menu_items = [
    {name = "About", url = "/about/"},
    {name = "Tags", url = "/tags/"},
    {name = "GitHub", url = "https://github.com/nikoook", newtab = true},
]
