title = "He's blog"
base_url = "https://nikoook.github.io/niko-zola-blog"

theme = "terminimal"
compile_sass = true

taxonomies = [
    {name = "tags"},
]

[markdown]
highlight_code = true

[extra]
accent_color = "blue"
background_color = "dark"
author = "Neo"
logo_text = "No need to conpare I am alone"
menu_items = [
    {name = "tags",  url = "/niko-zola-blog/tags/"},
    {name = "about", url = "/niko-zola-blog/about"},
    {name = "github", url = "https://github.com/nikoook", newtab = true},
]

enable_post_view_navigation = true
post_view_navigation_prompt = "Read more"
